"""integrations, imports, audit log

Revision ID: efbb83baf31b
Revises: d63f94e3380a
Create Date: 2026-09-20 15:11:03.728905
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'efbb83baf31b'
down_revision: str | None = 'd63f94e3380a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_sources',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_sources')),
    sa.UniqueConstraint('code', name=op.f('uq_integration_sources_code'))
    )
    op.create_table('audit_log',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('external_links',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['integration_sources.id'], name=op.f('fk_external_links_source_id_integration_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_links')),
    sa.UniqueConstraint('source_id', 'entity_type', 'external_id', name=op.f('uq_external_links_source_id'))
    )
    op.create_index(op.f('ix_external_links_entity_id'), 'external_links', ['entity_id'], unique=False)
    op.create_index(op.f('ix_external_links_source_id'), 'external_links', ['source_id'], unique=False)
    op.create_table('import_runs',
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('import_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='uploaded', nullable=False),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rows_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_import_runs_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_runs'))
    )
    op.create_table('integration_runs',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('triggered_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='running', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_received', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['integration_sources.id'], name=op.f('fk_integration_runs_source_id_integration_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('fk_integration_runs_triggered_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_runs'))
    )
    op.create_index(op.f('ix_integration_runs_source_id'), 'integration_runs', ['source_id'], unique=False)
    op.create_table('import_errors',
    sa.Column('import_run_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], name=op.f('fk_import_errors_import_run_id_import_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_errors'))
    )
    op.create_index(op.f('ix_import_errors_import_run_id'), 'import_errors', ['import_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_errors_import_run_id'), table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index(op.f('ix_integration_runs_source_id'), table_name='integration_runs')
    op.drop_table('integration_runs')
    op.drop_table('import_runs')
    op.drop_index(op.f('ix_external_links_source_id'), table_name='external_links')
    op.drop_index(op.f('ix_external_links_entity_id'), table_name='external_links')
    op.drop_table('external_links')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('integration_sources')
    # ### end Alembic commands ###
